---
- name: Install Visual Studio Code on Ubuntu Desktop
  hosts: all
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - wget
          - apt-transport-https
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add Microsoft GPG key
      ansible.builtin.apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Add Visual Studio Code repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
        state: present
        filename: vscode

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Visual Studio Code
      apt:
        name: code
        state: present
